## BC카드 소비 데이터 분석

#### 1. 데이터 로딩 및 확인

In [4]:
import pandas as pd

bc_data = pd.read_csv('./data/bccard_201906.csv', index_col=0)

bc_data.head(10)

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,80,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,40,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,83,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,80,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,80,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536
5,201906,11,서울특별시,1114,중구,11140540,회현동,10,T&E,11,...,내국인,47,경상북도,4713,경주시,2,30대,2,3759530,463
6,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,40,...,내국인,11,서울특별시,1150,강서구,2,20대,1,1461800,274
7,201906,11,서울특별시,1171,송파구,11710646,장지동,30,생활,70,...,내국인,11,서울특별시,1171,송파구,1,40대,3,557490,48
8,201906,11,서울특별시,1168,강남구,11680656,도곡2동,30,생활,40,...,내국인,45,전라북도,4511,전주시,2,30대,2,36909050,3465
9,201906,11,서울특별시,1114,중구,11140550,명동,10,T&E,20,...,내국인,28,인천광역시,2817,미추홀구,1,20대,1,10002400,117

In [5]:
bc_data.tail(10)

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99991,201906,11,서울특별시,1174,강동구,11740550,고덕1동,30,생활,40,...,내국인,41,경기도,4136,남양주시,2,40대,3,68980,15
99992,201906,11,서울특별시,1171,송파구,11710642,문정2동,10,T&E,21,...,내국인,11,서울특별시,1171,송파구,2,60대 이상,5,3350000,10
99993,201906,11,서울특별시,1132,도봉구,11320514,창4동,30,생활,40,...,내국인,41,경기도,4117,안양시,2,40대,3,12200,3
99994,201906,11,서울특별시,1168,강남구,11680545,압구정동,99,기타,91,...,내국인,11,서울특별시,1126,중랑구,1,30대,2,1432000,3
99995,201906,11,서울특별시,1114,중구,11140520,소공동,30,생활,40,...,내국인,45,전라북도,4511,전주시,1,40대,3,971830,13
99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,40,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,40,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,40,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,42,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,51,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [6]:
bc_data.shape

(100001, 23)

#### 2. 서울시 거주/비거주 고객 비교 분석

#### 2-1. 고객 수

In [ ]:
# 서울시 거주
seoul_customers = bc_data[bc_data['CSTMR_MEGA_CTY_NM'] == '서울특별시']
seoul_customers_count = len(seoul_customers)

# 서울시 비거주
non_seoul_customers = bc_data[bc_data['CSTMR_MEGA_CTY_NM'] != '서울특별시']
non_seoul_customers_count = len(non_seoul_customers)

data = [seoul_customers_count, non_seoul_customers_count]
df = pd.DataFrame(data, index=['서울시 거주', '서울시 비거주'], columns=['고객 수'])

df

          고객 수
서울시 거주   54150
서울시 비거주  45851

#### 2-2. 총 소비액

In [9]:
# 서울시 거주
seoul_total_amount = seoul_customers['AMT'].sum()

# 서울시 비거주
non_seoul_total_amount = non_seoul_customers['AMT'].sum()

df['총 소비액'] = [seoul_total_amount, non_seoul_total_amount]

df

          고객 수         총 소비액
서울시 거주   54150  119663142676
서울시 비거주  45851  146587135822

#### 2-3. 카드 이용 건수

In [10]:
# 서울시 거주
seoul_total_cnt = seoul_customers['CNT'].sum()

# 서울시 비거주
non_seoul_total_cnt = non_seoul_customers['CNT'].sum()

df['카드 이용 건수'] = [seoul_total_cnt, non_seoul_total_cnt]

df

          고객 수         총 소비액  카드 이용 건수
서울시 거주   54150  119663142676   5542462
서울시 비거주  45851  146587135822   4950200

#### 3. 서울시 편의점 소비 정보 분석

#### 3-1. 서울시 편의점 소비액, 강남구 편의점 소비액

In [ ]:
gangpyeon = bc_data[(bc_data['CTY_RGN_NM'] == '강남구') & (bc_data['TP_BUZ_NO'] == 4010)]

pyeon_total = bc_data[bc_data['TP_BUZ_NO'] == 4010]['AMT'].sum()
gn_total = bc_data[(bc_data['CTY_RGN_NM'] == '강남구')]['AMT'].sum()
gangpyeon_total = gangpyeon['AMT'].sum()
gn_live_total = gangpyeon[gangpyeon['CSTMR_CTY_RGN_NM'] == '강남구']['AMT'].sum()
non_gn_live_total = gangpyeon[gangpyeon['CSTMR_CTY_RGN_NM'] != '강남구']['AMT'].sum()

data = [pyeon_total, gn_total, gangpyeon_total, gn_live_total, non_gn_live_total]

df = pd.DataFrame(
    data, 
    index=[
        '편의점', 
        '강남구', 
        '강남구 편의점', 
        '강남구 거주자의 강남구 편의점', 
        '강남구 비거주자의 강남구 편의점'
    ],
    columns=[
        '소비액'
    ]
)

df

                           소비액
편의점                 7299184098
강남구                35535648502
강남구 편의점              707275140
강남구 거주자의 강남구 편의점     288379890
강남구 비거주자의 강남구 편의점    418895250